### ISSUE TITLE
Question : Write Variable

### ISSUE THREAD

**Issue by dre12** [NakWarsi/OPC_CLIENT_DotNet_Explorer#2]
Nice work. Do you have any idea how to write a variable with the ua .net standard ? 
I try some stuff from the Official UA.NetStandard page but had no luck.

**Comment by NakWarsi** [comment]
hi @dre12 
sorry for the late reply, 

Yes If you want to write to the node variables than you have to create a Method-State node at the server which you can call from the Client with a proper argument.

**Comment by NakWarsi** [comment]
I have to close this issue.
if you need any info, you can send me a mail (@gmail)
